### ISSUE TITLE
Pending license 

### ISSUE THREAD

**Issue by Ch-rode** [ThirdAILabs/Demos#19]
Hello,
thanks for your work !
I asked for the licence to try ThirdAI the 24/08 but unfortunately I am still waiting to be contacted. I also sent an email to contact@thirdai.com but still no answers.
Do you know after when I will be contacted? The mail I received said 48 hours.
Thank you

**Comment by JoshEngels** [comment]
Hi Chiara, sorry for the delay, previously we were focused on enterprise use cases. We are currently working on a student license and plan to have this ready in the next few weeks.

**Comment by sidjain3ai** [comment]
Hi Chiara, now you can use our demos.
