### ISSUE TITLE
TabularClassifier - Demo Step 2 Constructor Mismatch with Bolt 0.3.0

### ISSUE THREAD

**Issue by apsaltis** [ThirdAILabs/Demos#25]
Step 2: Defining the TabularClassifier model uses the following constructor:

classifier = bolt.TabularClassifier(model_size="medium", n_classes=n_classes)

Which is invalid only the following argument types are supported:
    1. thirdai._thirdai.bolt.TabularClassifier(internal_model_dim: int, n_classes: int, column_datatypes: List[str])

**Comment by JoshEngels** [comment]
We've resolved this now, thanks!
